version: '3.8'
services:

  app:
    build: .
#    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/code
    ports:
      - "8004:8000"  # 8004 so don't conflict with other dev
    restart: always